### ISSUE TITLE
Contact opnemen met een contactpersoon

### ISSUE THREAD

**Issue by DominicV1** [JSchoonveld/Regain#12]
Op de homepagina boven de footer moet een contactformulier komen waarmee een bezoeker vragen en opmerkingen kan sturen naar de beheerder van de website. De beheerder ontvangt een e-mail met de desbetreffende inhoud.

Invulvelden:

- Voornaam
- Achternaam
- e-mail
- mobiel (niet verplicht)
- bericht

Als `gebruiker`
Kan ik `een contact formulier invullen`
Zodat ik `een vraag of opmerking naar een contactpersoon kan versturen`

**Comment by JSchoonveld** [comment]
Contactformulier is gemaakt. Moet alleen na het weekend nog ervoor zorgen dat er ook een e-mail verstuurd wordt.
