### ISSUE TITLE
Bezoekersaantallen bekijken

### ISSUE THREAD

**Issue by DominicV1** [JSchoonveld/Regain#23]
Als `opdrachtgever` 
wil ik `de bezoekersaantallen van de website kunnen bekijken` 
zodat ik `inzicht heb in de populariteit en het bereik van de website.`

Wanneer er tijd over is is er een verzoek dat de opdrachtgever het verkeer op de website in kan zien. Zo kan hij/zij de stakeholders ook laten zien hoeveel bereik ze hebben. Voor eventuele doorontwikkeling kunnen er ook pijnpunten worden getraceerd. 

De systemen die we daar voor gaan gebruiken zijn:
 - Google Tag Manager
 - Google Analytics

**Comment by JSchoonveld** [comment]
Tjeerd moet eerst een Google analytics account aanmaken
