### ISSUE TITLE
Behoeftendocument

### ISSUE THREAD

**Issue by JSchoonveld** [JSchoonveld/Regain#7]
Het uitwerken van de behoefteanalyse voor Regain naar aanleiding van het gesprek met Adi S. op 12/06/2023.

Belangrijk

- Versie beheer
- pagina nummers
- namen
- klassen 
- studenten nummers 
- datum
- 

Inhoud van het document
- inhoud
- Inleiding/introductie
- Kern van het project
- Algemene beschrijving Regain
- Aanleiding van de opdracht
- ALgemene beschrijving opdracht
- Doelstellingen
- Doelgroepen
- Beschrijving vormgeving + wireframe
- Beschrijving algemene informatie
- Interactie analyse
- Vragen en antwoorden na aanleiding gesprek
- Eisen en Wensen
- Uit te voeren werkzaamheden
- Mogelijke risico's

**Comment by DominicV1** [comment]
[Regain-Behoefteanalyse-V1.pdf](https://github.com/JSchoonveld/Regain/files/11722830/Regain-Behoefteanalyse-V1.pdf)
